# Generated by Django 4.1 on 2022-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapps', '0005_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='BlankPic.jpg', upload_to='cover_photos'),
        ),
    ]
