# Generated by Django 4.1 on 2022-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapps', '0006_alter_post_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(default='BlankPic.jpg', upload_to='cover_photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
    ]
